module Tinkick
  type numeric_boost_number = Integer | Float | BigDecimal | String | nil

  type numeric_boost_options = { ?factor: numeric_boost_number, ?modifier: String | Symbol, ?missing: numeric_boost_number | false, ?boost_mode: String | Symbol | nil }

  type numeric_boost_spec = Array[String | Symbol] | Hash[String | Symbol, numeric_boost_options] | false | nil

  type where_boosts = filter_conditions | false | nil

  type legacy_boost = String | Symbol | false | nil

  class BoostBy
    MAX_SCORE: Float

    @model: singleton(ActiveRecord::Base)
    @sums: Array[[ String, String ]]
    @multipliers: Array[[ String, String ]]
    @warned: bool
    @conditions: Array[[ filter_conditions, Float ]]
    @conditional_scoring: bool
    @numeric_scoring: bool
    @recency_spec: recency_boost_spec
    @now: Time

    def initialize: (singleton(ActiveRecord::Base) model, numeric_boost_spec specification, ?boost_where: where_boosts, ?boost: legacy_boost, ?boost_by_recency: recency_boost_spec) -> void
    def empty?: () -> bool
    def score_sql: (String base_score) -> String

    private

    def compile_recency: () -> void

    def conditional_functions: (where_boosts specification) -> Array[[ filter_conditions, Float ]]
    def conditional_number: (filter_value value) -> Float
    def compile_conditions: () -> void
    def number: (numeric_boost_number value) -> Float
    def numeric_field: (String name) -> String
    def json_numeric_field: (String root, Array[String] path) -> String
    def modified: (String value, String modifier) -> String
    def group: (Array[[ String, String ]] functions, String operation) -> String
  end
end
