module Tinkick
  class LucenePattern
    type expression = String | RegexAutomaton

    MAX_INTEGER: Integer
    MAX_NESTING: Integer

    @work: RegexAutomaton::Work
    @characters: Array[String]
    @position: Integer
    @depth: Integer

    def initialize: (String source) -> void
    def compile: () -> RegexAutomaton

    private

    def union: () -> expression
    def intersection: () -> expression
    def sequence: () -> expression
    def repetition: () -> expression
    def complement: () -> expression
    def atom: () -> expression
    def class_part: () -> RegexAutomaton
    def predefined: () -> expression?
    def character: () -> String
    def interval: () -> RegexAutomaton
    def decimal: (String value) -> Integer
    def integer: () -> Integer
    def automaton: (expression expression) -> RegexAutomaton
    def peek: () -> String?
    def take: () -> String
    def consume: (String value) -> bool
    def expect: (String value) -> void
  end
end
