module Tinkick
  class QueryText
    type misspellings = bool | { ?transpositions: bool, ?edit_distance: Integer, ?distance: Integer, ?prefix_length: Integer, ?fields: Array[String | Symbol] }

    @connection: ActiveRecord::ConnectionAdapters::AbstractAdapter

    def initialize: (ActiveRecord::ConnectionAdapters::AbstractAdapter connection) -> void

    def compile: (String term, ?operator: String, ?match: Symbol, ?misspellings: misspellings) -> String

    def exclusion: (String term, words: Array[String], match: Symbol) -> String

    def tokens: (String term, ?analysis: Hash[String, String]) -> Array[String]

    private

    def quote: (String term) -> String

    def literal: (String word) -> String

    def partial: (String word, Symbol match) -> String

    def fuzzy_pattern: (String word, Symbol match, Integer distance, Integer prefix, bool transpositions) -> String

    def fuzzy: (String word, Integer distance, Integer prefix, bool transpositions) -> String

    def fuzzy_settings: (misspellings options) -> [ Integer, Integer, bool ]?
  end
end
