module Tinkick
  type relation_number = Integer | String | nil

  type relation_field = search_field | search_fields

  type relation_options = { fields: search_fields, misspellings: QueryText::misspellings, where: filter_conditions, order: query_order?, limit: relation_number, offset: relation_number, page: relation_number, per_page: relation_number, padding: relation_number, match: Symbol, operator: String | Symbol, load: bool?, total_entries: Integer?, countless: bool, keyset: bool, after: String?, aggs: aggregation_spec?, smart_aggs: bool, includes: association_spec?, model_includes: model_associations?, scope_results: result_scope?, select: source_selection?, exclude: exclusion_phrases, highlight: highlight_options, boost_by: numeric_boost_spec, boost_where: where_boosts, boost: legacy_boost, boost_by_recency: recency_boost_spec, conversions: conversion_fields, conversions_v2: conversion_v2, conversions_term: conversion_term }

  type relation_option_subset = { ?fields: search_fields, ?misspellings: QueryText::misspellings, ?where: filter_conditions, ?order: query_order?, ?limit: relation_number, ?offset: relation_number, ?page: relation_number, ?per_page: relation_number, ?padding: relation_number, ?match: Symbol, ?operator: String | Symbol, ?load: bool?, ?total_entries: Integer?, ?countless: bool, ?keyset: bool, ?after: String?, ?aggs: aggregation_spec?, ?smart_aggs: bool, ?includes: association_spec?, ?model_includes: model_associations?, ?scope_results: result_scope?, ?select: source_selection?, ?exclude: exclusion_phrases, ?highlight: highlight_options, ?boost_by: numeric_boost_spec, ?boost_where: where_boosts, ?boost: legacy_boost, ?boost_by_recency: recency_boost_spec, ?conversions: conversion_fields, ?conversions_v2: conversion_v2, ?conversions_term: conversion_term }

  class Relation
    include Enumerable[result_record]
    extend Forwardable

    class DefaultValue
    end

    NO_DEFAULT_VALUE: DefaultValue

    @term: Object?
    @options: relation_options
    @query: Query?
    @results: Results?

    attr_reader model: singleton(ActiveRecord::Base)
    alias klass model

    def initialize: (singleton(ActiveRecord::Base) model, ?Object? term, fields: search_fields, misspellings: QueryText::misspellings, ?where: filter_conditions, ?order: query_order?, ?limit: relation_number, ?offset: relation_number, ?page: relation_number, ?per_page: relation_number, ?padding: relation_number, ?match: Symbol, ?operator: String | Symbol, ?load: bool?, ?total_entries: Integer?, ?countless: bool, ?keyset: bool, ?after: String?, ?aggs: aggregation_spec?, ?smart_aggs: bool, ?includes: association_spec?, ?model_includes: model_associations?, ?scope_results: result_scope?, ?select: source_selection?, ?exclude: exclusion_phrases, ?highlight: highlight_options, ?boost_by: numeric_boost_spec, ?boost_where: where_boosts, ?boost: legacy_boost, ?boost_by_recency: recency_boost_spec, ?conversions: conversion_fields, ?conversions_v2: conversion_v2, ?conversions_term: conversion_term) -> void

    def loaded?: () -> bool
    def only: (*String | Symbol keys) -> Relation
    def except: (*String | Symbol keys) -> Relation
    def countless: (?bool value) -> Relation
    def countless!: (?bool value) -> Relation
    def keyset: (?after: String?) -> Relation
    def keyset!: (?after: String?) -> Relation
    def load: () -> Relation
            | (bool? value) -> Relation
    def load!: (bool? value) -> Relation
    def includes: (*association_spec values) -> Relation
    def includes!: (*association_spec values) -> Relation
    def model_includes: (model_associations values) -> Relation
    def model_includes!: (model_associations values) -> Relation
    def scope_results: (result_scope? value) -> Relation
    def scope_results!: (result_scope? value) -> Relation
    def select: (*source_fields values) -> Relation
              | (*source_fields values) { (result_record) -> boolish } -> Array[result_record]
    def select!: (*source_fields values) -> Relation
    def reselect: (*source_fields values) -> Relation
    def reselect!: (*source_fields values) -> Relation
    def exclude: (*exclusion_scalar | Array[exclusion_scalar] | nil values) -> Relation
    def exclude!: (*exclusion_scalar | Array[exclusion_scalar] | nil values) -> Relation
    def aggs: () -> Hash[String, aggregation_result]?
            | (*String | Symbol | aggregation_spec values, **aggregation_options options) -> Relation
    def aggs!: (*String | Symbol | aggregation_spec values, **aggregation_options options) -> Relation
    def smart_aggs: (bool value) -> Relation
    def smart_aggs!: (bool value) -> Relation
    def aggregations: () -> response_aggregations?

    def fields: (*relation_field values) -> Relation
    def fields!: (*relation_field values) -> Relation
    def where: () -> Where
             | (filter_conditions? value) -> Relation
    def where!: (filter_conditions value) -> Relation
    def rewhere: (filter_conditions value) -> Relation
    def rewhere!: (filter_conditions value) -> Relation
    def order: (*query_order values) -> Relation
    def order!: (*query_order values) -> Relation
    def reorder: (*query_order values) -> Relation
    def reorder!: (*query_order values) -> Relation
    def limit: (relation_number value) -> Relation
    def limit!: (relation_number value) -> Relation
    def offset: () -> Integer
              | (relation_number value) -> Relation
    def offset!: (relation_number value) -> Relation
    def page: (relation_number value) -> Relation
    def page!: (relation_number value) -> Relation
    def per_page: () -> Integer
                | (relation_number value) -> Relation
    def per: (relation_number value) -> Relation
    def per_page!: (relation_number value) -> Relation
    def padding: () -> Integer
               | (relation_number value) -> Relation
    def padding!: (relation_number value) -> Relation
    def match: (Symbol value) -> Relation
    def match!: (Symbol value) -> Relation
    def operator: (String | Symbol value) -> Relation
    def operator!: (String | Symbol value) -> Relation
    def misspellings: (QueryText::misspellings value) -> Relation
    def misspellings!: (QueryText::misspellings value) -> Relation
    def total_entries: () -> Integer
                     | (Integer? value) -> Relation
    def total_entries!: (Integer? value) -> Relation
    def first: () -> result_record?
             | (Integer limit) -> Array[result_record]
    def pluck: (*String | Symbol keys) -> Array[result_value]

    def each: () -> Enumerator[result_record, Array[result_record]]
            | () { (result_record) -> void } -> Array[result_record]
    def any?: () -> bool
            | (Object pattern) -> bool
            | () { (result_record) -> boolish } -> bool
    def empty?: () -> bool
    def size: () -> Integer
    alias length size
    def []: (Integer index) -> result_record?
          | (Integer start, Integer length) -> Array[result_record]?
          | (Range[Integer?] range) -> Array[result_record]?
    alias slice []
    def to_ary: () -> Array[result_record]
    def model_name: () -> ActiveModel::Name
    def entry_name: (?Hash[Symbol, Object?] options) -> String
    def missing_records: () -> Array[missing_record]
    def misspellings?: () -> bool
    def took: () -> Integer
    def error: () -> nil
    def hits: () -> Array[search_hit]
    def response: () -> search_response
    def boost: (legacy_boost value) -> Relation
    def boost!: (legacy_boost value) -> Relation
    def boost_by: (String | Symbol | Array[String | Symbol] | Hash[String | Symbol, numeric_boost_options] value) -> Relation
    def boost_by!: (String | Symbol | Array[String | Symbol] | Hash[String | Symbol, numeric_boost_options] value) -> Relation

    def boost_where: (filter_conditions value) -> Relation
    def boost_where!: (filter_conditions value) -> Relation
    def boost_by_recency: (Hash[String | Symbol, recency_boost_options] value) -> Relation
    def boost_by_recency!: (Hash[String | Symbol, recency_boost_options] value) -> Relation

    def highlight: (?highlight_options value) -> Relation
    def highlight!: (?highlight_options value) -> Relation
    def highlights: (?multiple: bool) -> Array[result_highlights]
    def with_highlights: (?multiple: bool) -> Enumerator[[ result_record, result_highlights ], Array[[ result_record, search_hit ]]]
                       | (?multiple: bool) { (result_record, result_highlights) -> void } -> Array[[ result_record, search_hit ]]
    def with_hit: () -> Enumerator[[ result_record, search_hit ], Array[[ result_record, search_hit ]]]
                | () { (result_record, search_hit) -> void } -> Array[[ result_record, search_hit ]]
    def total_count: () -> Integer
    def current_page: () -> Integer
    def limit_value: () -> Integer
    def total_pages: () -> Integer
    alias num_pages total_pages
    def offset_value: () -> Integer
    def previous_page: () -> Integer?
    alias prev_page previous_page
    def next_page: () -> Integer?
    def has_next_page?: () -> bool
    def next_cursor: () -> String?
    def first_page?: () -> bool
    def last_page?: () -> bool
    def out_of_range?: () -> bool
    def with_score: () -> Enumerator[[ result_record, Float ], Array[[ result_record, Float ]]]
                  | () { (result_record, Float) -> void } -> Array[[ result_record, Float ]]

    private

    def initialize_copy: (Relation other) -> void
    def check_loaded: () -> void
    def page_number: () -> Integer
    def page_size: () -> Integer
    def page_padding: () -> Integer
    def query: () -> Query
    def execute: () -> Results
  end

  class Where
    @relation: Relation

    def initialize: (Relation relation) -> void
    def not: (filter_conditions conditions) -> Relation
  end
end
