module Tinkick
  class TextMatch
    type predicate = [ String, Array[String] ]

    @model: singleton(ActiveRecord::Base)

    def initialize: (singleton(ActiveRecord::Base) model) -> void

    def highlight_matches: (Array[String?] texts, String term, match: Symbol, ?misspellings: QueryText::misspellings) -> Array[String?]

    def predicate: (String column_sql, String term, match: Symbol, ?misspellings: QueryText::misspellings) -> predicate

    private

    def normalize_sql: (String expression, bool case_sensitive, String? function) -> String

    def validate_misspellings!: (QueryText::misspellings options) -> void
  end
end
