module Tinkick
  module Generators
    class InstallGenerator < Rails::Generators::Base
      include ActiveRecord::Generators::Migration

      def create_migration_file: () -> void

      private

      def extensions: () -> Array[String]
    end
  end
end
